## provide the name of the namespace
namespace:
  name: staging

## define the image to execute with the Deployment
image:
  repository: maur1
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
## set the number of replicas for an application
replicaCount: 3
resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"

containerPort: 3111
livenessProbe:
  path: "/healthz"
readinessProbe:
  path: "/healthz"